/**
 * This map will map the icon to the todo state char
 */
export const iconMap:Map<string, string> = new Map([
  ['!', 'icons\\alert.png'],
  ['b', 'icons\\bookmark.png'],
  ['w', 'icons\\cake.png'],
  ['x', 'icons\\check.png'],
  ['S', 'icons\\dollar.png'],
  ['d', 'icons\\down.png'],
  ['u', 'icons\\up.png'],
  ['f', 'icons\\flame.png'],
  ['I', 'icons\\lightbulb.png'],
  ['i', 'icons\\info.png'],
  ['k', 'icons\\key.png'],
  ['<', 'icons\\left.png'],
  ['l', 'icons\\pin.png'],
  ['?', 'icons\\help.png'],
  ['>', 'icons\\right.png'],
  ['*', 'icons\\star.png'],
  ['p', 'icons\\pro.png'],
  ['c', 'icons\\contra.png'],
  [' ', 'icons\\circle.png'],
  ['1', 'icons\\1.png'],
  ['2', 'icons\\2.png'],
  ['3', 'icons\\3.png'],
  ['4', 'icons\\4.png'],
  ['5', 'icons\\5.png'],
  ['6', 'icons\\6.png'],
  ['7', 'icons\\7.png'],
  ['8', 'icons\\8.png'],
  ['9', 'icons\\9.png'],
]);
